# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(LiblineaR)
    library(parsnip)
    library(recipes)
    library(textrecipes)
    library(workflows)
}
b <- board_folder(path = "models")
v <- vetiver_pin_read(b, "lego-sets")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
